### ISSUE TITLE
[RFE] Need a release of FLUO with arm64 support

### ISSUE THREAD

**Issue by sdlarsen** [flatcar/flatcar-linux-update-operator#178]
## Current situation

The support has been merged quite a while, but we're still missing a release supporting arm64.

## Impact

Holding back production use of arm64

## Ideal future situation

A new release soon'ish

**Comment by invidian** [comment]
I created a PR with changelog https://github.com/flatcar/flatcar-linux-update-operator/pull/179. Once merged, rc1 release will be created and I will create regular release probably next week if there is no complaints.

**Comment by invidian** [comment]
v0.9.0 is now out which supports arm64.
