### ISSUE TITLE
Example-Deployment: PodSecurityPolicy deprecated/removed

### ISSUE THREAD

**Issue by a2yp** [flatcar/flatcar-linux-update-operator#182]
## Current situation

Used the [examples](https://github.com/flatcar/flatcar-linux-update-operator/tree/master/examples/deploy) to deploy – `kubent` says PodSecurityPolicy is deprecated/removed:
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.25 <<<
------------------------------------------------------------------------------------------
KIND                NAMESPACE     NAME                            API_VERSION      REPLACE_WITH (SINCE)
PodSecurityPolicy   <undefined>   flatcar-linux-update-agent      policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy   <undefined>   flatcar-linux-update-operator   policy/v1beta1   <removed> (1.21.0)

## Impact

Possible issues when upgrading Kubernetes to 1.25 – haven't tried yet.

## Ideal future situation

Do not use the deprecated/removed PodSecurityPolicy and replace it in the examples.

**Comment by invidian** [comment]
Good point. I just checked with kind and it indeed fails to install. More than that, existing instruction for existing deployment also does not work anymore as we added kustomize support. I'll fix both soon.
