### ISSUE TITLE
Configuring reboot window using flags as documented is not working

### ISSUE THREAD

**Issue by steled** [flatcar/flatcar-linux-update-operator#193]
## Description

Hi, I setup a reboot window of 2 hours via the environment variables but the reboot is not done during this window.

## Impact

The node is not rebooted during the reboot window and does not get the new update.

## Environment and steps to reproduce

1. **Set-up**: I setup FLUO as described at the [Usage](https://github.com/flatcar/flatcar-linux-update-operator#usage) section
2. **Task**: for the reboot window I added the following lines to the `update-operator.yaml` file:

```yaml
        env:
        ...
        - name: UPDATE_OPERATOR_REBOOT_WINDOW_START
          value: "09:00"
        - name: UPDATE_OPERATOR_REBOOT_WINDOW_LENGTH
          value: "2h"
````

3. **Action(s)**: to trigger an update I'm [jumping to another channel](https://www.flatcar.org/docs/latest/setup/releases/switching-channels/#jump-to-another-channel-with-flatcar-update)
4. **Error**: the node isn't rebooted during the reboot window

## Expected behavior

The node with the update should be rebooted during the reboot window

## Additional information

I can see that the labels and annotaions changes:

```console
Labels:             flatcar-linux-update.v1.flatcar-linux.net/group=stable
                    flatcar-linux-update.v1.flatcar-linux.net/id=flatcar
                    flatcar-linux-update.v1.flatcar-linux.net/reboot-needed=true
                    flatcar-linux-update.v1.flatcar-linux.net/version=3374.2.5
                    v1.kubeone.io/operating-system=flatcar
Annotations:        flatcar-linux-update.v1.flatcar-linux.net/last-checked-time: 1679986757
                    flatcar-linux-update.v1.flatcar-linux.net/new-version: 3510.1.0
                    flatcar-linux-update.v1.flatcar-linux.net/reboot-in-progress: false
                    flatcar-linux-update.v1.flatcar-linux.net/reboot-needed: true
                    flatcar-linux-update.v1.flatcar-linux.net/status: UPDATE_STATUS_UPDATED_NEED_REBOOT
```

I can't see any problems from the logs of the pod:

```console
$ kubectl logs -n reboot-coordinator flatcar-linux-update-operator-85b99fd865-swqgc
I0328 06:58:07.376415       1 main.go:108] /bin/update-operator running
I0328 06:58:07.376546       1 leaderelection.go:248] attempting to acquire leader lease reboot-coordinator/flatcar-linux-update-operator-lock...
I0328 06:58:07.401639       1 leaderelection.go:258] successfully acquired lease reboot-coordinator/flatcar-linux-update-operator-lock
I0328 06:58:08.382212       1 operator.go:593] Found 0 rebooted nodes
<for the sake of brevity>
I0328 07:18:47.188086       1 operator.go:593] Found 0 rebooted nodes
```

And I see the environment variables correctly set to the pod:

```console
kubectl exec -it -n reboot-coordinator flatcar-linux-update-operator-85b99fd865-swqgc -- sh
/bin $ env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
HOSTNAME=flatcar-linux-update-operator-85b99fd865-swqgc
SHLVL=1
UPDATE_OPERATOR_REBOOT_WINDOW_START=09:00
HOME=/
TERM=xterm
UPDATE_OPERATOR_REBOOT_WINDOW_LENGTH=2h
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
POD_NAMESPACE=reboot-coordinator
KUBERNETES_SERVICE_HOST=10.96.0.1
PWD=/bin
```

## Additional question

Is it possible to set the reboot window only for office working hours, for example:

```console
UPDATE_OPERATOR_REBOOT_WINDOW_START: Mon, Tue, Wed, Thu, Fri 09:00
UPDATE_OPERATOR_REBOOT_WINDOW_LENGTH: 8h
```

**Comment by invidian** [comment]
Good finding. It seems those environment variables were documented in cda5e86e1c00d4976ad43b85830216b1c4ea7dc7, but never implemented. They should be removed from the documentation.

Separately, we can discuss whether it make sense to actually implement it, as right now I don't see an obvious benefit in doing so. Is there some specific reason you would prefer to use environment variables instead of CLI flags?

**Comment by steled** [comment]
Ok, I think I found the problem...
The time in the pod is GMT but we are at GMT +2

So 2 questions:

Is it possible to update the timezone for the pod?
Is it possible to set the reboot window only for office working hours, for example:
```console
UPDATE_OPERATOR_REBOOT_WINDOW_START: Mon, Tue, Wed, Thu, Fri 09:00
UPDATE_OPERATOR_REBOOT_WINDOW_LENGTH: 8h
```

**Comment by steled** [comment]
Ok, I opened [[RFE] Add support for multiple reboot windows](https://github.com/flatcar/flatcar-linux-update-operator/issues/195)

This ticket than can be closed...

Thanks for your support 👍
