### ISSUE TITLE
Update happens out of configured reboot window

### ISSUE THREAD

**Issue by oboudry-mvp** [flatcar/flatcar-linux-update-operator#201]
## Description

Also /bin/update-operator is running with reboot-window parameters, two nodes in my cluster rebooted completely out of the configured window (11AM also configured for 2AM)

```
$ k exec -it -n reboot-coordinator pods/flatcar-linux-update-operator-6c667d6d98-vkhwc -- sh
/bin $ ps
PID   USER     TIME  COMMAND
    1 nobody    0:10 /bin/update-operator --reboot-window-start=02:00 --reboot-window-length=1h
   28 nobody    0:00 sh
   34 nobody    0:00 ps
```

I suspected Locksmith, but locksmithd has been masked from the start in the ignition file, as per documentation.

```
systemd:
  units:
    - name: locksmithd.service
      mask: true
    - name: update-engine.service
      enabled: true
```

Which can also be verified on the nodes:

```
core@flatcar01 ~ $ sudo systemctl status locksmithd.service
○ locksmithd.service
     Loaded: masked (Reason: Unit locksmithd.service is masked.)
     Active: inactive (dead)

```

Below is the describe of the Flatcar update operator that was running at the time of reboot. It also shows the reboot-window schedule parameters.

```
$ k describe -n reboot-coordinator pod/flatcar-linux-update-operator-6c667d6d98-bg2qs
Name:             flatcar-linux-update-operator-6c667d6d98-bg2qs
Namespace:        reboot-coordinator
Priority:         0
Service Account:  flatcar-linux-update-operator-sa
Node:             flatcar01/192.168.77.101
Start Time:       Wed, 15 Nov 2023 08:03:16 +0000
Labels:           app=flatcar-linux-update-operator
                  pod-template-hash=6c667d6d98
Annotations:      cni.projectcalico.org/containerID: 085edefbfe9f05cfcc9f2d2bb3c15d470c023e60acdbf68c5af14bc312ada143
                  cni.projectcalico.org/podIP:
                  cni.projectcalico.org/podIPs:
Status:           Failed
Reason:           Terminated
Message:          Pod was terminated in response to imminent node shutdown.
IP:
IPs:              <none>
Controlled By:    ReplicaSet/flatcar-linux-update-operator-6c667d6d98
Containers:
  update-operator:
    Container ID:  containerd://475d590e78a3ca6a9da08f936199ff694b68c87ad5f481ff2c5d0b7046b60c52
    Image:         ghcr.io/flatcar/flatcar-linux-update-operator:v0.9.0
    Image ID:      ghcr.io/flatcar/flatcar-linux-update-operator@sha256:67a2c3c23dd94b9e56aeb87b41d7d2176fea681861fb70b015c7ca8b18165cdd
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/update-operator
    Args:
      --reboot-window-start=02:00
      --reboot-window-length=1h
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 15 Nov 2023 08:03:18 +0000
      Finished:     Wed, 22 Nov 2023 11:05:26 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      POD_NAMESPACE:  reboot-coordinator (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qxjrw (ro)
Conditions:
  Type               Status
  DisruptionTarget   True
  Initialized        True
  Ready              False
  ContainersReady    False
  PodScheduled       True
Volumes:
  kube-api-access-qxjrw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

## Impact

Potential service outage at unexpected time.

## Environment and steps to reproduce

1. Setup 3 nodes of Flatcar 3602.2.1
2. Deploy flatcar-linux-update-operator, patching the example for defining the maintenance window.
![image](https://github.com/flatcar/flatcar-linux-update-operator/assets/79530946/603acbc6-1d1d-4cc3-a220-7d569f10db37)
3. Wait for next update.

## Expected behavior

Update and reboot happening between 2AM and 3AM UTC.

## Additional data

Nodes have the right UTC time and are in sync with ntp, I even checked the time within the update operator container.

**Comment by invidian** [comment]
Thanks for reporting @oboudry-mvp. Could you please provide operator logs around this undesired update? Logs will also be useful to confirm that it was the operator which scheduled an update (or reboot, actually).

I looked again at:
```go
func (k *Kontroller) insideRebootWindow() bool {
  if k.rebootWindow == nil {
    return true
  }

  // Most recent reboot window might still be open.
  mostRecentRebootWindow := k.rebootWindow.Previous(time.Now())

  return time.Now().Before(mostRecentRebootWindow.End)
}
```

And tired it out with associated test:
```go
func Test_Foo(t *testing.T) {
  t.Parallel()

  periodic, err := operator.ParsePeriodic("02:00", "1h")
  if err != nil {
    t.Fatalf("Periodic parse failed: %v", err)
  }

  ref := mustParseTime("Wed Nov 22 02:01:00 UTC 2023")
  mostRecentRebootWindow := periodic.Previous(ref)

  t.Errorf("Inside? %t", ref.Before(mostRecentRebootWindow.End))

  outsideRef := mustParseTime("Wed Nov 22 01:59:59 UTC 2023")

  lastRebootWindow := periodic.Previous(outsideRef)

  t.Errorf("Inside? %t", outsideRef.Before(lastRebootWindow.End))

  nextRef := mustParseTime("Wed Nov 22 03:00:01 UTC 2023")

  nextRebootWindow := periodic.Previous(nextRef)

  t.Errorf("Inside? %t", nextRef.Before(nextRebootWindow.End))
}

```

which seem to produce expected result:
```console
$ go test ./pkg/operator/ -run ^Test_Foo
--- FAIL: Test_Foo (0.00s)
    periodic_test.go:110: Inside? true
    periodic_test.go:116: Inside? false
    periodic_test.go:122: Inside? false
FAIL
FAIL    github.com/flatcar/flatcar-linux-update-operator/pkg/operator   0.010s
FAIL
```

I'd also check the time reported in operator container? Maybe it has different timezone configured for some reason?

**Comment by oboudry-mvp** [comment]
Hi Mateusz,

Please find the logs attached. I copied two logs, the update-operator-logs-1.log (in Error below) is the update operator which got stopped by the reboot (was running for 7 days), and the update-operator-logs-2.log is the update-operator which was restarted automatically when the first one stopped.

***@***.***

Not sure how to read these, but I'm afraid I don't see any node reboot logged in there. But if it's not FLUO which rebooted the nodes, I really don't understand where the reboots came from, as my flatcar01 and flatcar02 nodes did reboot in sequence, and were upgraded to a newer version. Knowing I disabled Locksmith on all 3 nodes, I suspected it could only be FLUO. Sorry if it's not FLUO triggered, in which case I'll struggle to understand what did update the nodes.

Time on PC (in domain), on management host, and on core nodes all matching (apart the PM format instead of 24h for the management host)
***@***.***

Time in update-operator also matching PC time
***@***.***

Thanks,

Olivier.

**Comment by invidian** [comment]
@oboudry-mvp It seems GitHub does not parse attachments when replying to issue via email. Can you share those logs somehow differently? You might be able to attach them via GitHub UI or alternatively, put it in a service like pastebin and share a link?

**Comment by oboudry-mvp** [comment]
Sorry for this, I thought it would parse the e-mail properly. I edited the previous reply to make it more readable. Images are not visible directly, but they should be accessible via the links. As it comes from an e-mail, the system no longer wants to render it with Markdown.

Here are the logs:

[update-operator-logs.zip](https://github.com/flatcar/flatcar-linux-update-operator/files/13442715/update-operator-logs.zip)

**Comment by invidian** [comment]
Hm, and do you happen to have agent logs? I'm wondering if agent detected that a reboot is required? From the operator logs, it indeed seems that operator was not involved in those reboots, so indeed configured reboot window would not be effective. And are you 100% sure nodes have received update and rebooted with agent running?

**Comment by oboudry-mvp** [comment]
Yes, nodes flatcar01 and flatcar02 have been rebooted and updated, both in a row.

If you look at the uptime and version of flatcar01
![image](https://github.com/flatcar/flatcar-linux-update-operator/assets/79530946/0f1b636c-7e39-4959-b987-2e9bee79a950)

and flatcar02 you'll see that flatcar02 has about 5 min less runtime than flatcar01, both have version 3602.2.2 and had 3602.2.1 the day before (I survey them closely as I just started using FLUO)
![image](https://github.com/flatcar/flatcar-linux-update-operator/assets/79530946/be7623a1-70d0-49f0-bf51-1a96dd383a80)

By the way, yesterday flatcar03 was updated within maintenance window (at 2AM UTC) and it's mentionned in update operator log.
![image](https://github.com/flatcar/flatcar-linux-update-operator/assets/79530946/77532953-f933-44ba-bea3-1f144d52a1ce)

This is the log and shows flatcar03 requiring reboot.
![image](https://github.com/flatcar/flatcar-linux-update-operator/assets/79530946/619f52d7-c100-4ba2-99b4-0d5e5e965ec2)

All 3 nodes have been setup from the exact same ignition configuration file. I generate the config file from a script and the only element that changes is the name and IP that I give on command line. I really don't understand how they can differ in reboot behaviour.

I looked at a portion of the agent log (the one running flatcar02). It started after reboot.
```
I1122 11:07:19.012130       1 main.go:84] /bin/update-agent running
I1122 11:07:19.014844       1 agent.go:145] Setting info labels
I1122 11:07:19.070075       1 agent.go:151] Checking annotations
I1122 11:07:19.074199       1 agent.go:174] Setting annotations map[string]string{"flatcar-linux-update.v1.flatcar-linux.net/reboot-in-progress":"false", "flatcar-linux-update.v1.flatcar-linux.net/reboot-needed":"false"}
I1122 11:07:19.109119       1 agent.go:212] Waiting for ok-to-reboot from controller...
I1122 11:07:19.109277       1 agent.go:362] Beginning to watch update_engine status
I1122 11:07:19.111390       1 agent.go:306] Updating status
W1122 11:11:32.832442       1 agent.go:227] Error waiting for an ok-to-reboot: waiting for annotation "flatcar-linux-update.v1.flatcar-linux.net/reboot-ok": watch closed before UntilWithoutRetry timeout
I1122 11:11:32.832477       1 agent.go:212] Waiting for ok-to-reboot from controller...
I1122 11:13:41.385674       1 agent.go:306] Updating status
I1122 11:13:41.873588       1 agent.go:306] Updating status
I1122 11:57:21.444849       1 agent.go:306] Updating status
I1122 11:57:21.609757       1 agent.go:306] Updating status
W1122 12:07:55.385464       1 agent.go:227] Error waiting for an ok-to-reboot: waiting for annotation "flatcar-linux-update.v1.flatcar-linux.net/reboot-ok": watch closed before UntilWithoutRetry timeout
I1122 12:07:55.385489       1 agent.go:212] Waiting for ok-to-reboot from controller...
W1122 12:42:13.113478       1 agent.go:227] Error waiting for an ok-to-reboot: waiting for annotation "flatcar-linux-update.v1.flatcar-linux.net/reboot-ok": watch closed before UntilWithoutRetry timeout
I1122 12:42:13.113504       1 agent.go:212] Waiting for ok-to-reboot from controller...
I1122 12:43:48.444956       1 agent.go:306] Updating status
I1122 12:43:48.612496       1 agent.go:306] Updating status
```

But flatcar03 has the same warning, so not sure if I should worry about that:
```
I1123 02:02:19.693430       1 main.go:84] /bin/update-agent running
I1123 02:02:19.694522       1 agent.go:145] Setting info labels
I1123 02:02:22.829376       1 agent.go:151] Checking annotations
I1123 02:02:22.833939       1 agent.go:174] Setting annotations map[string]string{"flatcar-linux-update.v1.flatcar-linux.net/reboot-in-progress":"false", "flatcar-linux-update.v1.flatcar-linux.net/reboot-needed":"false"}
I1123 02:03:10.589978       1 agent.go:188] Marking node as schedulable
I1123 02:03:10.611900       1 agent.go:198] Setting annotations map[string]string{"flatcar-linux-update.v1.flatcar-linux.net/agent-made-unschedulable":"false"}
I1123 02:03:10.687706       1 agent.go:212] Waiting for ok-to-reboot from controller...
I1123 02:03:10.687766       1 agent.go:362] Beginning to watch update_engine status
I1123 02:03:10.688347       1 agent.go:306] Updating status
I1123 02:07:40.068058       1 agent.go:306] Updating status
I1123 02:07:41.061579       1 agent.go:306] Updating status
W1123 02:34:42.297395       1 agent.go:227] Error waiting for an ok-to-reboot: waiting for annotation "flatcar-linux-update.v1.flatcar-linux.net/reboot-ok": watch closed before UntilWithoutRetry timeout
I1123 02:34:42.297445       1 agent.go:212] Waiting for ok-to-reboot from controller...
I1123 02:51:40.062449       1 agent.go:306] Updating status
I1123 02:51:40.370234       1 agent.go:306] Updating status
```

**Comment by invidian** [comment]
Hm, and can you look into system journal on nodes 01 and 02 right before the reboot? Or compare it with the same logs from 03? It seems to me both operator and agent behaved correctly with node 03, so it's unlikely that it's an operator which rebooted 01 and 02. Did nodes 01 and 02 shut down gracefully prior to reboot?

**Comment by oboudry-mvp** [comment]
Thanks for the advice, did not know I could find all the logs in the journalctl. On flatcar01 I found the following logs around the reboot time. It looks like locksmithd

```
Nov 22 11:00:25 flatcar01 locksmithd[3554]: LastCheckedTime=1700650763 Progress=0 CurrentOperation="UPDATE_STATUS_UPDATED_NEED_REBOOT" NewVersion=3602.2.2 NewSize=372757373
Nov 22 11:00:25 flatcar01 locksmithd[3554]: No configured reboot window
Nov 22 11:00:25 flatcar01 locksmithd[3554]: Logins detected, delaying reboot for 5 minutes.
```

But I don't understand why it did run as it is masked:
```
core@flatcar01 ~ $ sudo systemctl status locksmithd
○ locksmithd.service
     Loaded: masked (Reason: Unit locksmithd.service is masked.)
     Active: inactive (dead)
```

And masking was done at installation via the following ignition file:

```
variant: flatcar
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa XXXXXXXXXX
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: HOSTNAME
    - path: /etc/systemd/network/00-eno1.network
      contents:
        inline: |
          [Match]
          Name=eno1
    
          [Network]
          DNS=192.168.77.13
          DNS=192.168.77.11
          Address=IPADDRESS/24
          Gateway=192.168.77.10
systemd:
  units:
    - name: locksmithd.service
      mask: true
    - name: update-engine.service
      enabled: true
```

Looking at the logs, I realize I masked locksmithd.service after reboot manually instead of through the ignition file, and I suppose I let locksmithd run in the background. Node 3 was installed from the updated ignition file.
```
Oct 31 10:20:27 flatcar01 locksmithd[3554]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="reboot"
Oct 31 14:20:51 flatcar01 sudo[192335]:     core : TTY=pts/0 ; PWD=/home/core ; USER=root ; COMMAND=/usr/bin/systemctl mask locksmithd.service
```

So the reboot windows works great when configured properly.

Thanks for your help troubleshooting this, and sorry for creating an issue that was not one.
